[package]
name = "frame-support-storage-fuzzer"
version = "0.1.0"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2021"
license = "Apache-2.0"
homepage = "https://substrate.io"
repository = "https://github.com/paritytech/substrate/"
description = "Fuzz FRAME storage types"
publish = false

[[bin]]
name = "paged-list"
path = "src/paged_list.rs"

[dependencies]
arbitrary = "1.3.0"
honggfuzz = "0.5.49"

frame-support = { path = "../", default-features = false, features = ["std"] }
sp-io = { path = "../../../primitives/io", default-features = false, features = ["std"] }
